services:
  db:
    image: postgres:16
    container_name: smart-planner-postgres
    environment:
      POSTGRES_DB: smart-planner
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5439"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
